car_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from car_inventory.forms import UserLoginForm
from car_inventory.models import User, db, check_password_hash

# Imports for flask login
from flask_login import login_user, logout_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

# Two methods GET -> gets the form and POST -> allows the form to post
@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            # Print just to confirm it worked
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form Inputs')

    return render_template('signup.html',form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:

        if request.method == 'POST' and form.validate_on_submit():
            # if true, get the email from the form
            email = form.email.data
            password = form.password.data
            # Print just to check to make sure it's working
            print(email,password)

 
            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: via email/password', 'auth-success')
                return redirect(url_for('site.home'))

 
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')

    return render_template('signin.html', form=form)


@auth.route('/logout')
# Need to import login_required
@login_required
def logout():
    # Need to import logout_user
    logout_user()
    return redirect(url_for('site.home'))

car_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html') 

@site.route('/blog')
def blog():
    return render_template('blog.html')


@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Rangers 59 - Car Inventory Home</title>
</head>
<body>

 <!--Navigation Bar Start-->
<div class="container">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color:#fff;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{  url_for('site.home')  }}">
                <img class="navbar-brand" src="../static/images/logo_resized.png" alt="Rangers 59 Car Inventory Logo"class="d-inline-block align-text-top src">
                Rangers 59
            </a>
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('site.home') }}">Home</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">How it Works</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">Support</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Rangers 59</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('site.profile') }}">Profile</a>
                    </li>

                </ul>

                
            <form class="d-flex">
                
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}"><button class="btn btn-outline-success button1" type="button">Log Out</button>
                </a>

                {% else %}
                <a href="{{ url_for('auth.signin') }}"><button class="btn btn-outline-success button1" type="button">Sign In</button>
                </a>

                <a href="{{ url_for('auth.signup') }}"><button class="btn btn-outline-success button2" type="button">Sign Up for Free</button>
                </a>
                {% endif %}

            </form>
        </div>
    </nav>
</div>
<!--End of Navigation Bar-->


    <!-- Set up block content for Flask -->
    {% block content %}
    {% endblock content %}    

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>
</html>

car_inventory/templates/form.html
<!-- HTML Produced By the Flask Form -->
<!-- add a POST method -->
<form method="POST">
    <!-- Hidden means it's hidden from view unless looking at inspect -->
    {{ form.hidden_tag() }}
    
    <!-- form-group is a bootstrap class -->
    <div class="form-group">

        <fieldset id="email-field">
            <!-- call on the variables for the form -->
            <!-- see forms.py to find that the name is 'email' by looking at the position of the arguments within the class attributes/variables -->
                {{ form.email.label }}
                {{ form.email(class = 'form-control',placeholder = "Place Email Here") }}
        </fieldset>

        <fieldset id='pass-field'>
            {{ form.password.label }}
            {{ form.password(class = 'form-control',placeholder = "Place Password Here")}}
        </fieldset>

        <!-- Submit Button -->
        {{ form.submit_button(class = "btn btn-primary") }}


    </div>
</form>